name: orcestra_book
channels:
  - conda-forge
dependencies:
  - python==3.12
  - aiohttp
  - cartopy
  - cmocean
  - dask>=2023.2.0
  - docutils==0.17.1  # see https://github.com/executablebooks/jupyter-book/issues/1997
  - fsspec!=0.9.0 # 0.9.0 has a bug which leads to incomplete reads via HTTP
  - geopy
  - healpy
  - intake-xarray
  - intake[dataframe]<2.0.0 # since intake 0.6.1 to_dask() doesn't work anymore without the [dataframe] specification due to a missing msgpack dependency
  - jinja2
  - jupyter-book
  - matplotlib<3.9 # required until there's a new release of healpy (see https://github.com/healpy/healpy/pull/944)
  - netcdf4
  - numpy
  - requests
  - scipy<1.14.0 # required by easy.gems
  - xarray
  - zarr>=2.8.3
  - pip
  - pip:
    - easygems>=0.0.3
    - orcestra>0.0.8
    - pybtex-apa-style
